### PR TITLE
Updated Readme.md to reflect Laravel 5

### PR DESCRIPTION
**Pull request by jonathan-bird**

### CODE REVIEW

**Comment by Stayallive** [comment]
This does not reflect all changes actually (I temp remove migrations and such), I was not planning on putting this on Packagist actually... are you using/wanting to use this fork?

**Comment by Stayallive** [comment]
Thanks for submitting the pull request but I went ahead and implemented it my own with all required doc changes.

**Comment by jonathan-bird** [comment]
Sorry, been busy! Awesome

**Comment by Stayallive** [comment]
No problemo :+1:

**Pull request closed without merging**
