### PR TITLE
Rename migrations files to fix Windows compatibilities.

### PR DESCRIPTION
**Pull request by tortuetorche**
Otherwise it's impossible to `git clone` this repository on Windows.

FYI, on the original repository `machuga/authority-l4`, the migrations names are OK.

### CODE REVIEW

**Comment by tortuetorche** [comment]
@Stayallive Can you merge this pull request and tag a new release, please ? Because I need it to fix my [`authority-controller`](https://github.com/efficiently/authority-controller/tree/2.0) package which depends on your fork.

**Comment by Stayallive** [comment]
I must be blind, but what did you change exactly? :smile:

**Comment by tortuetorche** [comment]
Maybe :laughing:,
I've renamed:
`2013_04_08_175033_create_roles_table.php 2013_04_08_175033_create_roles_table.php` to `2013_04_08_175033_create_roles_table.php`.
And `2013_04_08_175152_create_role_user_table.php 2013_04_08_175152_create_role_user_table.php` to `2013_04_08_175152_create_role_user_table.php`

I don't know how did you this but my pull request fixes it.

**Comment by Stayallive** [comment]
Well.. okay sure, but I'm pretty sure this states 3 times exactly the same name :wink: 

screen shot 2015-02-27 at 19 18 23

**Comment by tortuetorche** [comment]
Thank you!

**Comment by tortuetorche** [comment]
I can confirm now that my `authority-controller` [demo](https://github.com/efficiently/laravel_authority-controller_app/tree/2.0#readme) is working with Windows and `authority-l5` 2.4.1 
:sunglasses:

**Comment by Stayallive** [comment]
Like a bawz!




Thanks for you contribution although I still have not a single clue on what you changed :)

**Comment by tortuetorche** [comment]
Read again this [comment](https://github.com/Stayallive/authority-l5/pull/3#issuecomment-76443784) and You would understand. I hope :wink:

**Comment by Stayallive** [comment]
Oh wow, my mail missed that last bit... now I feel stupid that I did not see that in the message xD Thanks :)

**Pull request merged**
